<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Ups P&aacute;gina no encontrada</title>
</head>

<body>
<h2>Ups P&aacute;gina no encontrada</h2>
<img src="http://www.cesarcancino.com/images/images.jpeg" />
<a href="<?php echo Conectar::ruta();?>c-home/" title="Salir de aqu&iacute;">Salir de aqu&iacute;</a>
</body>
</html>