<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Listado de Personas</title>
</head>

<body>
<?php include("menu.phtml");?>

Hola bienvenido a mi sitio web ya está logueado



<?php include("footer.phtml");?>
</body>
</html>