<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Listado de Personas</title>
</head>

<body onload="document.form.reset();document.form.login.focus();">
<?php //include("menu.phtml");?>

<h3>Ingrese sus datos para acceder al sistema</h3>
<form name="form" action="" method="post">
User : <input type="text" name="login" />
<br />
Password : <input type="password" name="pass" />
<br />
<br />
<input type="hidden" name="grabar" value="si" />
<input type="submit" value="Ingresar" title="Ingresar" />
</form>



<?php include("footer.phtml");?>
</body>
</html>