<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Listado de Personas</title>
</head>

<body onload="document.form.reset();document.form.nom.focus();">
<?php include("menu.phtml");?>

<!--********Formulario registro usuarios********-->



<form name="form" action="" method="post">
<?php
if (isset($_GET) and $_GET["valor"]=="1")
{
	?>
    <h2 style="color:#F00;">El usuario ha sido creado correctamente</h2>
    <?php
}
?>

<h2>Registrar Usuarios Nuevos</h2>
Nombre : <input type="text" name="nom" />
<br />
E-Mail : <input type="text" name="correo" />
<br />
Teléfono : <input type="text" name="tel" />
<br />
Login : <input type="text" name="login" />
<br />
Contraseña : <input type="password" name="pass" />
<br />
Dirección : <textarea name="dir" cols="30" rows="5"></textarea>
<hr />
<input type="hidden" name="grabar" value="si" />
<input type="submit" value="Registrar Nuevo Usuario" title="Registrar Nuevo Usuario" />
</form>
<!--****fin Formulario registro usuarios********-->


<?php include("footer.phtml");?>
</body>
</html>